name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Env
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          env|sort
      - name: this step will fail
        id: willfail
        continue-on-error: true
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          ls mysuperfile
      - name: reportfailure1
        if: failure() && steps.willfail.outcome == 'failure'
        run: |
          echo "step willfail has indeed failed"
      - name: this step will pass
        id: willpass
        run: |
          date
      - name: reportfailure2
        if: failure() && steps.willpass.outcome == 'failure'
        run: |
          echo "step willpass has also failed"
      - name: this step will fail again
        continue-on-error: true
        id: willfail2
        run: |
          ls mysuperfile2
      - name: reportfailure2
        if: failure() && steps.willfail2.outcome == 'failure'
        run: |
          echo "step willfail2 has indeed failed"
