name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Env
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          env|sort
      - name: this step will fail
        continue-on-error: true
        id: willfail
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          ls mysuperfile
      - name: reportfailure1
        if: steps.willfail.outputs.exit_code != 0
        run: |
          echo "step willfail has indeed failed"
      - name: this step will pass
        continue-on-error: true
        id: willpass
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          date
      - name: reportfailure2
        continue-on-error: true
        if: failure() && steps.willpass.outputs.exit_code != 0
        run: |
          echo "step willpass has also failed"
