name: Context Output
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Github Context
        run: echo "${{ toJSON(github) }}"
      - name: Echo Job Context
        run: echo "${{ toJSON(job) }}"
      - name: Echo Runner Context
        run: echo "${{runner}}"
      - name: Echo Env Context
        run: echo "${{ toJSON(env) }}"
      - name: Echo Inputs Context
        run: echo "${{ secrets }}"
      - name: Printing python info
        run: |
          echo "`which python` --version`"
          `which python` --version`
          echo "`which pytho3` --version`"
          `which pytho3` --version`
          echo "`which python2` --version`"
          `which python2` --version`
