name: Test and Deploy

# on: [push, workflow_dispatch]
on:
  push:
    branches:
      - master
      - main
      - dev*
      - dev**
    paths-ignore:
      - ".github/workflows/*"
  pull_request:
    types:
      - opened
    branches:
      - master
      - main
      - dev*
      - dev**
    paths-ignore:
      - ".github/workflows/*"
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [1.18, 1.19]
        include:
          - version: 1.17
            os: ubuntu-latest
        exclude:
          - version: 1.19
            os: windows-latest
    runs-on: ${{ matrix.os }}
    # runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: "^${{ matrix.version }}"
      - name: Install dependencies
        run: go mod vendor
      - name: Run Tests
        continue-on-error: true
        id: run-tests
        run: go test ./...
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install golang 1.18.2
        uses: actions/setup-go@v4
        with:
          go-version: "^1.18.2"
      - name: Install dependencies
        run: go install golang.org/x/lint/golint@latest
      - name: Go lint
        run: golint ./...
      - name: Go vet
        run: go vet ./...
      - name: Run Tests
        run: go test -v ./...
      - name: Build binary
        run: go build -v ./...
  report:
    needs: [test]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: output information
        run: |
          echo "Something went wrong"
          echo "${{ github }}"
  reusablejob:
    needs: test
    uses: ./.github/workflows/reusable.yml
